<?php
/**
 * @file
 * mnn_site_sections.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function mnn_site_sections_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Media Policy',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '035846f5-90dc-463f-b85f-d39593e0e225',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'Clip of the Week',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0a24ee3f-9e0c-4017-8303-65b19a31f718',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'About Us',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0a84e4a1-4f32-4bdb-95fa-4db1cbc78cf5',
    'vocabulary_machine_name' => 'sections',
  );
  $terms[] = array(
    'name' => 'Chuck\'s Picks',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '187f91b8-9624-4194-8a81-ac93597c0ee6',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'MNN Youth Channel',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2278c906-1251-401e-97ba-b321041499d4',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'Firehouse',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3110173b-dc1f-4bdb-b12b-a10b1fc06029',
    'vocabulary_machine_name' => 'sections',
  );
  $terms[] = array(
    'name' => 'Media',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '42c001b9-f87a-495a-8c53-4d51d5317983',
    'vocabulary_machine_name' => 'sections',
  );
  $terms[] = array(
    'name' => 'Classes',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '45639bbd-deea-4ee7-97ee-571c143689ae',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'MNN Diaries',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '6ce75fd3-0927-4c44-b491-f62fa9e3a640',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'News and Views',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '7ff57872-5b68-471f-9be0-35e582716c1a',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'Media Education',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '87a044fd-1273-45d8-b072-fc5e4b06693f',
    'vocabulary_machine_name' => 'sections',
  );
  $terms[] = array(
    'name' => 'News',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '89b6bc78-8599-4538-af57-9da1cbd343da',
    'vocabulary_machine_name' => 'sections',
  );
  $terms[] = array(
    'name' => 'Race2Represent',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8a3bed6d-3f51-4566-a096-afb08fee5d03',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'Events',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8d5ea9f8-b121-4d09-a0ae-4769e0754a6e',
    'vocabulary_machine_name' => 'sections',
  );
  $terms[] = array(
    'name' => 'Programming Highlights',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8de74a8c-0ad9-4544-9db7-bf4cf998b891',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'MNN El Barrio Firehouse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8ffc4fb0-98e6-4c1f-8138-a494721183ce',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'Events',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'd77fb1fd-abde-419c-93be-e166adf5ceb5',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'Community Media',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'edf7679d-bcc7-40d4-b227-2e190326d7ee',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  $terms[] = array(
    'name' => 'Program Guide',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fbbf34d5-f286-4f25-8269-aba0b313fdba',
    'vocabulary_machine_name' => 'sections',
    'parent' => array(
      0 => '89b6bc78-8599-4538-af57-9da1cbd343da',
    ),
  );
  return $terms;
}
